apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-zero
  labels: 
    app: app-zero
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-zero
  template:
    metadata:
      labels:
        app: app-zero
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.10
        env:
        - name: MESSAGE
          value: "App0"
        ports:
        - containerPort: 8080

